# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: pip
    directory: / # Location of package manifests
    schedule:
      interval: daily
    assignees:
      - "fabelx"
    reviewers:
      - "fabelx"
    rebase-strategy: auto
    commit-message:
      prefix: "fix pip"
      prefix-development: "fix pip dev"
      include: scope
    labels:
      - "pip"
      - "dependencies"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: disabled
    commit-message:
      prefix: chore
      include: scope
