# Usage:
#   pip install pre-commit
#   pre-commit install
#   pre-commit run --all-files
#   pre-commit autoupdate
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
# The configuration of black and isort is automatically loaded
# from either pyproject.toml to remain consistent with the Makefile
# targets.
- repo: https://github.com/psf/black
  rev: 23.12.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
