name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # default values: opened, synchronize, or reopened
    types:
      - opened
      - synchronize
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"

permissions:
  contents: read

jobs:
  run-tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.platform }}"
    strategy:
      matrix:
        python-version: [ '3.12' ]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        make install-test
    - name: "Run tests"
      run: make test

  build:
    name: "Build & verify package"
    needs: run-tests
    strategy:
      matrix:
        python-version: [ '3.12' ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          make install-dev
      - name: "Build package"
        run: make build
      - name: "Twine check"
        run: make twine-check
